import pickle
import numpy as np
from music21 import instrument, note, stream, chord
from src.model import create_network
import os

def generate_music(model_weights_path='models/final_model.keras', filename='output/generated_music.mid'):
    """ Generate a piano midi file """
    
    if not os.path.exists('data/notes.pkl'):
        raise FileNotFoundError("data/notes.pkl not found. Please run preprocess.py first.")
        
    # load the notes used to train the model
    with open('data/notes.pkl', 'rb') as filepath:
        notes = pickle.load(filepath)

    # Get all pitch names
    pitches = sorted(set(item for item in notes))
    n_vocab = len(set(notes))

    print("Loading network...")
    # Prepare inputs again just to get a random starting point
    network_input, normalized_input = prepare_sequences(notes, pitches, n_vocab)
    model = create_network(normalized_input, n_vocab)
    model.load_weights(model_weights_path)

    print("Generating notes...")
    prediction_output = generate_notes(model, network_input, pitches, n_vocab)
    
    print("Saving MIDI file...")
    create_midi(prediction_output, filename=filename)
    
def prepare_sequences(notes, pitches, n_vocab):
    """ Prepare the sequences used by the Neural Network """
    # map between notes and integers and back
    note_to_int = dict((note, number) for number, note in enumerate(pitches))

    sequence_length = 100
    if len(notes) <= sequence_length:
        sequence_length = max(1, len(notes) - 1)

    network_input = []
    
    for i in range(0, len(notes) - sequence_length, 1):
        sequence_in = notes[i:i + sequence_length]
        network_input.append([note_to_int[char] for char in sequence_in])

    n_patterns = len(network_input)

    # reshape the input into a format compatible with LSTM layers
    normalized_input = np.reshape(network_input, (n_patterns, sequence_length, 1))
    # normalize input
    normalized_input = normalized_input / float(n_vocab)

    return network_input, normalized_input

def generate_notes(model, network_input, pitches, n_vocab):
    """ Generate notes from the neural network based on a sequence of notes """
    # pick a random sequence from the input as a starting point for the generation
    start = np.random.randint(0, len(network_input)-1)

    int_to_note = dict((number, note) for number, note in enumerate(pitches))

    pattern = network_input[start]
    prediction_output = []

    # generate 150 notes
    for note_index in range(150):
        prediction_input = np.reshape(pattern, (1, len(pattern), 1))
        prediction_input = prediction_input / float(n_vocab)

        prediction = model.predict(prediction_input, verbose=0)

        index = np.argmax(prediction)
        result = int_to_note[index]
        prediction_output.append(result)

        pattern.append(index)
        pattern = pattern[1:len(pattern)]

    return prediction_output

def create_midi(prediction_output, filename='output/generated_music.mid'):
    """ convert the output from the prediction to notes and create a midi file from the notes """
    offset = 0
    output_notes = []

    if not os.path.exists('output'):
        os.makedirs('output')

    # create note and chord objects based on the values generated by the model
    for pattern in prediction_output:
        # pattern is a chord
        if ('.' in pattern) or pattern.isdigit():
            notes_in_chord = pattern.split('.')
            notes = []
            for current_note in notes_in_chord:
                new_note = note.Note(int(current_note))
                new_note.storedInstrument = instrument.Piano()
                notes.append(new_note)
            new_chord = chord.Chord(notes)
            new_chord.offset = offset
            output_notes.append(new_chord)
        # pattern is a note
        else:
            new_note = note.Note(pattern)
            new_note.offset = offset
            new_note.storedInstrument = instrument.Piano()
            output_notes.append(new_note)

        # increase offset each iteration so that notes do not stack
        offset += 0.5

    midi_stream = stream.Stream(output_notes)
    midi_stream.write('midi', fp=filename)
    print(f"Generated MIDI saved to {filename}")

def generate_phonk_music(filename='output/generated_music.mid'):
    """ Generate a premium syncopated Phonk MIDI file with melody, bass, and drums """
    import random
    from music21 import stream, note, chord, duration, tempo, instrument
    
    score = stream.Score()
    
    # 1. Lead Melody Part (Cowbell style)
    lead_part = stream.Part()
    lead_part.insert(0, instrument.Cowbell())
    lead_part.insert(0, tempo.MetronomeMark(number=138)) # Standard Phonk Tempo: 138 BPM
    
    # 2. Electric Bass Part
    bass_part = stream.Part()
    bass_part.insert(0, instrument.ElectricBass())
    
    # 3. Drum Part (using General MIDI Percussion Mapping)
    drum_part = stream.Part()
    drum_part.insert(0, instrument.SnareDrum())
    
    # Dark Phonk Scale (E Minor / E Phrygian)
    scale = ['E5', 'G5', 'A5', 'A#5', 'B5', 'D6', 'E6'] # Includes blue note A#5 (tritone)
    bass_scale = ['E2', 'G2', 'A2', 'B2', 'C2', 'D2']
    
    # Build 16 bars of trap-phonk goodness
    offset = 0.0
    
    # Generate 4-bar motifs to make it sound structured and catchy
    motifs = []
    for _ in range(4):
        # A motif is 8 steps (each step is 0.5 beats - eighth note)
        step_notes = []
        for step in range(8):
            if random.random() < 0.65:
                step_notes.append(random.choice(scale))
            else:
                step_notes.append(None)
        motifs.append(step_notes)
        
    for bar in range(16):
        # Select motif based on structure (AABA or similar)
        motif_idx = bar % 4
        if bar % 4 == 3 and random.random() < 0.5:
            motif = [random.choice(scale) if random.random() < 0.7 else None for _ in range(8)] # Variation bar
        else:
            motif = motifs[motif_idx]
            
        # Select bass note for this bar (E2 or G2 or A2)
        if bar % 4 == 0 or bar % 4 == 2:
            bass_note_pitch = 'E2'
        elif bar % 4 == 1:
            bass_note_pitch = 'G2'
        else:
            bass_note_pitch = 'A2'
            
        for i in range(8):
            step_time = offset + (i * 0.5)
            
            # Melodic Lead (Cowbell)
            note_pitch = motif[i]
            if note_pitch:
                n = note.Note(note_pitch)
                n.duration = duration.Duration(0.5)
                n.storedInstrument = instrument.Cowbell()
                lead_part.insert(step_time, n)
                
            # Heavy Bass note (plays on beat 1 and beat 3)
            if i == 0:
                b = note.Note(bass_note_pitch)
                b.duration = duration.Duration(2.0) # 2 beats
                b.storedInstrument = instrument.ElectricBass()
                bass_part.insert(step_time, b)
            elif i == 4:
                # Bass slide/variation
                next_bass = random.choice(bass_scale)
                b = note.Note(next_bass)
                b.duration = duration.Duration(2.0)
                b.storedInstrument = instrument.ElectricBass()
                bass_part.insert(step_time, b)
                
            # Phonk Drum Pattern
            # Kick
            if i == 0 or i == 5:
                k = note.Note(36)
                k.duration = duration.Duration(0.5)
                k.storedInstrument = instrument.SnareDrum()
                drum_part.insert(step_time, k)
                
            # Snare
            if i == 2 or i == 6:
                s = note.Note(38)
                s.duration = duration.Duration(0.5)
                s.storedInstrument = instrument.SnareDrum()
                drum_part.insert(step_time, s)
                
            # Hi-hats (every 0.5 beat)
            h = note.Note(42)
            h.duration = duration.Duration(0.25)
            h.storedInstrument = instrument.SnareDrum()
            drum_part.insert(step_time, h)
            
            # Double-time roll (sixteenth note)
            if random.random() < 0.35:
                hr = note.Note(42)
                hr.duration = duration.Duration(0.25)
                hr.storedInstrument = instrument.SnareDrum()
                drum_part.insert(step_time + 0.25, hr)
                
        offset += 4.0 # 4 beats per bar
        
    score.append(lead_part)
    score.append(bass_part)
    score.append(drum_part)
    
    score.write('midi', fp=filename)
    print(f"Generated Phonk MIDI saved to {filename}")

if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser(description="Generate AI Music")
    parser.add_argument("model_weights", nargs="?", default="models/final_model.keras")
    parser.add_argument("output_path", nargs="?", default="output/generated_music.mid")
    parser.add_argument("--genre", "-g", default="piano", choices=["piano", "phonk"])
    args = parser.parse_args()
    
    if args.genre == 'phonk':
        generate_phonk_music(args.output_path)
    else:
        generate_music(args.model_weights, args.output_path)
